# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tokens'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tokens',
            table='tokens',
        ),
    ]
