# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='user_type',
            field=models.CharField(default=b'admin', max_length=255),
        ),
    ]
