# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('language_code', models.CharField(max_length=10)),
                ('hackerrank_name', models.CharField(default=None, max_length=20)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
    ]
